In [1]:
import pandas as pd
import numpy as np

# Clases propias
from etl import Dataloader
from feature_engineer import add_features
from train import Train
from train_with_mlflow import TrainWithMLflow

# Modelos
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
from xgboost import XGBClassifier

# MLflow
import mlflow

c:\Users\Valentina Molina\Documents\repositorios\Proyecto_Final_MLOps\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

ETL

In [2]:
loader = Dataloader(
    path_to_save=r"C:/Users/Valentina Molina/Documents/Repositorios/Proyecto_Final_MLOps/data/PS_20174392719_1491204439457_log.csv",
    n_samples=50000
)
df = loader.load_data()
loader.drop_name_columns()
df = loader.df.copy()

print(df.shape)
df.head()

(50000, 8)

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0

Feature Engineering

In [3]:
df = add_features(df)
df.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,diff_old_new_orig,diff_old_new_dest,amount_to_orig_balance,amount_to_dest_balance
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0,9839.64,0.0,0.057834,9839.640000
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0,1864.28,0.0,0.087731,1864.280000
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1,181.00,0.0,0.994505,181.000000
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1,181.00,21182.0,0.994505,0.008545
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0,11668.14,0.0,0.280788,11668.140000

Definir variables

In [4]:
numeric_features = [
    'step', 'amount',
    'oldbalanceOrg', 'newbalanceOrig',
    'oldbalanceDest', 'newbalanceDest',
    'diff_old_new_orig', 'diff_old_new_dest',
    'amount_to_orig_balance', 'amount_to_dest_balance'
]

categorical_features = ['type']
target_column = 'isFraud'
test_size = 0.2

Step 1: Modelando sin MLflow

In [5]:
# Logistic Regression
model = LogisticRegression(max_iter=1000, random_state=42)
trainer = Train(df, numeric_features, categorical_features, target_column, model, test_size)
pipeline = trainer.train()
print("Modelo Logistic Regression entrenado sin MLflow ✅")

# Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
trainer = Train(df, numeric_features, categorical_features, target_column, model, test_size)
pipeline = trainer.train()
print("Modelo RandomForest entrenado sin MLflow ✅")

Modelo Logistic Regression entrenado sin MLflow ✅
Modelo RandomForest entrenado sin MLflow ✅

Step 2: Modelando con MLflow (Logistic + RandomForest + LightGBM)

In [6]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("fraude-modelos")

mlflow.sklearn.autolog()

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb

modelos = [
    ("LogisticRegression", LogisticRegression(max_iter=1000, random_state=42)),
    ("RandomForest", RandomForestClassifier(n_estimators=100, random_state=42)),
    ("LightGBM", lgb.LGBMClassifier(random_state=42))
]

In [7]:
resultados = {}
for nombre, modelo in modelos:
    print(f"\nEntrenando {nombre} con MLflow...")
    trainer = TrainWithMLflow(df, numeric_features, categorical_features, target_column, modelo, test_size)
    pipeline, run_id = trainer.train()
    resultados[nombre] = run_id

resultados

Entrenando LogisticRegression con MLflow...
MLflow Run ID: 9f3ea05123e24a04bf4d523621f1c8c1
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.9984
Test Accuracy: 0.9978
🏃 View run popular-sow-876 at: http://127.0.0.1:5000/#/experiments/729808979030306957/runs/9f3ea05123e24a04bf4d523621f1c8c1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/729808979030306957

Entrenando RandomForest con MLflow...
MLflow Run ID: 9a87f2d2fff5458fa0731f29ce49dee7
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 1.0000
Test Accuracy: 0.9997
🏃 View run debonair-snail-974 at: http://127.0.0.1:5000/#/experiments/729808979030306957/runs/9a87f2d2fff5458fa0731f29ce49dee7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/729808979030306957

Entrenando LightGBM con MLflow...
[LightGBM] [Info] Number of positive: 80, number of negative: 39920
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004894 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2315
[LightGBM] [Info] Number of data points in the train set: 40000, number of used features: 15
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.002000 -> initscore=-6.212606
[LightGBM] [Info] Start training from score -6.212606
MLflow Run ID: f26493cd72ce4cf99b1a1253d8d0160e
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.9978
Test Accuracy: 0.9953
🏃 View run enthused-mole-206 at: http://127.0.0.1:5000/#/experiments/729808979030306957/runs/f26493cd72ce4cf99b1a1253d8d0160e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/729808979030306957

{'LogisticRegression': '9f3ea05123e24a04bf4d523621f1c8c1',
 'RandomForest': '9a87f2d2fff5458fa0731f29ce49dee7',
 'LightGBM': 'f26493cd72ce4cf99b1a1253d8d0160e'}

Modelo con XGBoost + MLflow

In [8]:
mlflow.set_experiment("fraude-xgboost")
mlflow.xgboost.autolog()

params_xgb = {
    "n_estimators": 100,
    "max_depth": 6,
    "learning_rate": 0.1,
    "subsample": 0.8
}

model_xgb = XGBClassifier(**params_xgb, random_state=42, use_label_encoder=False, eval_metric="logloss")

trainer = TrainWithMLflow(df, numeric_features, categorical_features, target_column, model_xgb, test_size, params_xgb, mlflow)
pipeline, run_id = trainer.train()
print("Modelo XGBoost entrenado con MLflow ✅", run_id)

MLflow Run ID: 275a9ce0ba55471abfb6f2fcd06edeea
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 1.0000
Test Accuracy: 0.9994
🏃 View run bold-robin-160 at: http://127.0.0.1:5000/#/experiments/432587766316071821/runs/275a9ce0ba55471abfb6f2fcd06edeea
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/432587766316071821
Modelo XGBoost entrenado con MLflow ✅ 275a9ce0ba55471abfb6f2fcd06edeea

Step 3: Modelo con MLflow + Optuna

In [9]:
from train_with_mlflow_optuna import TrainWithMLflowOptuna

mlflow.set_experiment("fraude-optuna")

param_distributions = {
    'n_estimators': ('int', 50, 200),
    'max_depth': ('int', 5, 30),
    'min_samples_split': ('int', 2, 10),
    'min_samples_leaf': ('int', 1, 5),
    'max_features': ('categorical', ['sqrt', 'log2', None])
}

trainer = TrainWithMLflowOptuna(
    df=df,
    numeric_features=numeric_features,
    categorical_features=categorical_features,
    target_column=target_column,
    model_class=RandomForestClassifier,
    test_size=0.2,
    n_trials=20,
    optimization_metric='f1',
    param_distributions=param_distributions,
    model_params={'random_state': 42},
    mlflow_setup=mlflow
)

best_pipeline, run_id, study = trainer.train()
print("Mejor modelo con Optuna:", run_id)

2025/09/22 19:19:55 INFO mlflow.tracking.fluent: Experiment with name 'fraude-optuna' does not exist. Creating a new experiment.
[I 2025-09-22 19:19:55,630] A new study created in memory with name: no-name-25d89609-9aef-46db-b4df-3da7b95d537a
2025/09/22 19:19:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '7bb5bb5bf9c84045bc9b9d9c2893c9f1', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run unleashed-carp-945 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/7bb5bb5bf9c84045bc9b9d9c2893c9f1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:20:23,866] Trial 0 finished with value: 0.918918918918919 and parameters: {'n_estimators': 178, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:20:24 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'aed7621db02847399b4093176186c509', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run receptive-mare-860 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/aed7621db02847399b4093176186c509
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:20:50,566] Trial 1 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 199, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:20:50 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6fbdae4ae72742c3ae03aa94f921873b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run masked-cod-816 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/6fbdae4ae72742c3ae03aa94f921873b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:21:05,443] Trial 2 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 54, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:21:05 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '4e098939459f4f2fa5acf8918f7003c2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run stylish-cub-95 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/4e098939459f4f2fa5acf8918f7003c2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:21:31,319] Trial 3 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 166, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:21:31 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '5178df52c49147d49439506f06221a79', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run thundering-calf-433 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/5178df52c49147d49439506f06221a79
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:21:53,082] Trial 4 finished with value: 0.918918918918919 and parameters: {'n_estimators': 75, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:21:53 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '80721f1a45e04d7e90882fe27071d0b2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run bald-horse-307 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/80721f1a45e04d7e90882fe27071d0b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:22:18,319] Trial 5 finished with value: 0.918918918918919 and parameters: {'n_estimators': 130, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:22:18 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '87e289d8ff6646b7bd193d9a729c8ced', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run brawny-shoat-556 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/87e289d8ff6646b7bd193d9a729c8ced
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:24:08,911] Trial 6 finished with value: 0.6470588235294118 and parameters: {'n_estimators': 197, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:24:09 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'bc5898b0650c4aba8b5f6a55ef29c09f', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run respected-seal-646 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/bc5898b0650c4aba8b5f6a55ef29c09f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:24:33,030] Trial 7 finished with value: 0.918918918918919 and parameters: {'n_estimators': 61, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:24:33 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd380b38ddd204a68b065cfe5ec40c564', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run upbeat-mule-77 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/d380b38ddd204a68b065cfe5ec40c564
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:25:02,321] Trial 8 finished with value: 0.918918918918919 and parameters: {'n_estimators': 141, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:25:02 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '536681f00aae46eebffe24db3f6377d2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run delicate-finch-306 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/536681f00aae46eebffe24db3f6377d2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:25:32,843] Trial 9 finished with value: 0.918918918918919 and parameters: {'n_estimators': 160, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:25:33 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '2251de7b572140caa51e24d982f4acda', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run useful-slug-718 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/2251de7b572140caa51e24d982f4acda
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:26:31,581] Trial 10 finished with value: 0.7222222222222222 and parameters: {'n_estimators': 96, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:26:31 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '46a0544fee394711ab0016d599e76925', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run sassy-frog-915 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/46a0544fee394711ab0016d599e76925
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:26:57,324] Trial 11 finished with value: 0.918918918918919 and parameters: {'n_estimators': 98, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:26:57 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'dcef98fe951548a284bd216db13467fe', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run selective-mink-559 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/dcef98fe951548a284bd216db13467fe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:27:20,557] Trial 12 finished with value: 0.918918918918919 and parameters: {'n_estimators': 99, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:27:20 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd40f96143b874376a94ae08e648e12d3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run spiffy-quail-28 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/d40f96143b874376a94ae08e648e12d3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:27:45,899] Trial 13 finished with value: 0.918918918918919 and parameters: {'n_estimators': 74, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:27:46 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '54c04155ba0340799830dfa4a8f6e083', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run sneaky-shad-287 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/54c04155ba0340799830dfa4a8f6e083
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:29:13,942] Trial 14 finished with value: 0.6470588235294118 and parameters: {'n_estimators': 173, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:29:14 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '140a34c523e741a0bc13edc4c50797c2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run languid-vole-320 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/140a34c523e741a0bc13edc4c50797c2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:29:36,224] Trial 15 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 114, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:29:36 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '28e8a78618b7493ba944ae56ce444ce1', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run selective-pig-530 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/28e8a78618b7493ba944ae56ce444ce1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:29:57,277] Trial 16 finished with value: 0.918918918918919 and parameters: {'n_estimators': 75, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:29:57 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '1684029fcc45453d9e9f72dcc3ac248c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run mysterious-eel-950 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/1684029fcc45453d9e9f72dcc3ac248c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:30:27,422] Trial 17 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 149, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:30:28 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '8587bd062e964d78becc79ec39838386', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run nebulous-hound-834 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/8587bd062e964d78becc79ec39838386
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:30:56,212] Trial 18 finished with value: 0.8888888888888888 and parameters: {'n_estimators': 180, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:30:56 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6545a5bfca8245b6a439f92d59885c1e', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run wistful-shrimp-428 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/6545a5bfca8245b6a439f92d59885c1e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644

[I 2025-09-22 19:32:09,085] Trial 19 finished with value: 0.7222222222222222 and parameters: {'n_estimators': 123, 'max_depth': 24, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 0.918918918918919.
2025/09/22 19:32:09 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '418eef99c4cb49959f19a77bea1d4bb0', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run gifted-shrew-11 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/418eef99c4cb49959f19a77bea1d4bb0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644
Optuna best params: {'random_state': 42, 'n_estimators': 178, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2'}
MLflow run_id: 79b2e99a85dc463e99a617ed18e3eff1
🏃 View run auspicious-rook-185 at: http://127.0.0.1:5000/#/experiments/438737474763045644/runs/79b2e99a85dc463e99a617ed18e3eff1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/438737474763045644
Mejor modelo con Optuna: 79b2e99a85dc463e99a617ed18e3eff1